server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activiti_study?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password: root

  #activiti配置
  activiti:
    check-process-definitions: true
    database-schema-update: true
    async-executor-activate: false   # 是否打开异步执行器
    history-level: full
#打印activiti执行的sql
logging:
  level:
    org.activiti.engine.impl.persistence.entity: trace
    org.activiti.engine.impl.persistence.entity.JobEntity: info  #定时任务